# This is a basic workflow that is manually triggered

name: New Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        branches: [ master ]
        inputs:
            version:
                # Friendly description to be shown in the UI instead of 'name'
                description: 'New Version'
                # Default value if no value is explicitly provided
                default: 'v1.0.0'
                # Input has to be provided for the workflow to run
                required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Build with Maven
                run: mvn -B package --file pom.xml
            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
                with:
                    tag_name: ${{ github.event.inputs.version }}
                    release_name: ${{ github.event.inputs.version }}
                    body: |
                        Changes in this Release
                        - First Change
                        - Second Change
                    draft: false
                    prerelease: false
